language: python
python:
  - 3.8

import:
  - credentials.yml

jobs:
  include:
    - stage: Test
      name: Test
      script:
        - ./test_heatbed.sh

    - stage: Merge
      name: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh | tee merge.log